# Generated by Django 4.1.7 on 2023-03-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0004_rename_specializaion_adddoctor_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddoctor',
            name='image',
            field=models.ImageField(default='', upload_to='img/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adddoctor',
            name='specialization',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
