# Generated by Django 4.1.7 on 2023-03-17 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0005_adddoctor_image_alter_adddoctor_specialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='short_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='docotor_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='docotor_specialization',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_gender',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adddoctor',
            name='image',
            field=models.ImageField(upload_to='static/img/doctor/'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='message',
            field=models.TextField(),
        ),
    ]
