# Generated by Django 4.1.7 on 2023-03-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0006_remove_doctor_short_name_doctor_docotor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_contact', models.CharField(max_length=100)),
                ('patient_addess', models.CharField(max_length=100)),
                ('patients_doctor', models.CharField(max_length=100)),
                ('patient_admit_date', models.DateField()),
                ('patient_release_date', models.DateField()),
                ('patient_days_spent', models.CharField(max_length=199)),
                ('patient_age', models.CharField(max_length=100)),
                ('patient_last_visit', models.CharField(max_length=100)),
                ('patient_status', models.CharField(max_length=100)),
                ('patient_diease_symptoms', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_patient',
            },
        ),
    ]
