# Generated by Django 4.1.7 on 2023-03-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0007_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_addess',
            new_name='patient_address',
        ),
    ]
