# Generated by Django 4.1.7 on 2023-03-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0008_rename_patient_addess_patient_patient_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_diease_symptoms',
            new_name='patient_disease_symptoms',
        ),
    ]
