# Generated by Django 4.1.7 on 2023-03-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0010_alter_patient_patient_disease_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=100)),
                ('medicine_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_pharmacy',
            },
        ),
    ]
