# Generated by Django 4.1.7 on 2023-03-21 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0011_pharmacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='docotor_address',
            new_name='doctor_address',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='docotor_specialization',
            new_name='doctor_specialization',
        ),
    ]
