# Generated by Django 4.1.7 on 2023-03-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0012_rename_docotor_address_doctor_doctor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('duty_time', models.CharField(max_length=100)),
                ('duty_ward', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'app_staff',
            },
        ),
    ]
