# Generated by Django 4.1.7 on 2023-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0015_alter_staff_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_admit_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_release_date',
            field=models.DateField(null=True),
        ),
    ]
