# Generated by Django 4.1.7 on 2023-03-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0016_alter_patient_patient_admit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
