# Generated by Django 4.1.7 on 2023-03-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0017_alter_staff_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/staff'),
        ),
    ]
