# Generated by Django 4.1.7 on 2023-04-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0018_alter_staff_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='static/image/service')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('last_updated_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'app_service',
            },
        ),
    ]
