# Generated by Django 4.1.7 on 2023-04-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0019_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=199)),
                ('Contact', models.CharField(max_length=199)),
                ('previous_medical_history', models.CharField(max_length=199)),
            ],
            options={
                'db_table': 'app_pricing',
            },
        ),
    ]
