# Generated by Django 4.1.7 on 2023-04-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0020_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='Contact',
            new_name='contact',
        ),
    ]
