# Generated by Django 4.1.7 on 2023-04-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0021_rename_contact_price_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='age',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
