# Generated by Django 4.1.7 on 2023-04-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0022_price_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='tablet',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
