# Generated by Django 4.1.7 on 2023-04-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hospital_system', '0024_contactus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read')], max_length=100, null=True),
        ),
    ]
